name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      is_release:
        description: 'Is this a release build?'
        type: boolean
        required: true
        default: false

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller shiv wheel tencentcloud-sdk-python-common

    - name: Create version
      if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.is_release) }}
      run: |
        "VERSION = VERSION + '+$(git rev-parse --short HEAD)'" | Out-File -FilePath "edgeone_update/version.py" -Append -Encoding utf8

    - name: Build project
      run: |
        shiv -e edgeone_update.edgeone_update:main -o edgeone_update.pyz .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          edgeone_update.pyz
          *.json
          LICENSE
        if-no-files-found: error
